source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftyVerticalScrollBar_Example' do
  pod 'SwiftyVerticalScrollBar', :path => '../'
end

target 'SwiftyVerticalScrollBar_Tests' do
  pod 'SwiftyVerticalScrollBar', :path => '../'

  
end
